### ISSUE TITLE
Do not use `simple_query` with user-specified data. Resort to prepared statements for tha

### ISSUE THREAD

**Issue by davidpodhola** [hsharpsoftware/rust-realworld-example-app#32]
See https://github.com/steffengy/tiberius/issues/17#issuecomment-303075092.

**Comment by steffengy** [comment]
@davidpodhola 
FYI I improved the ergonomics of prepared statements when only used once in
the latest master.

If you do not want to execute the same prepared statement more than once, 
you can now simply do
```rust
conn.query("SELECT xyz ... WHERE xy=@P1", &[&val]);
```
insteadof using `simple_query`.

If not, use `conn.prepare` as in some examples.
(Only make sense when you plan to execute the same statement multiple times, since
using the string as above would prepare the statement for each call).

**Comment by davidpodhola** [comment]
@steffengy great, thanks, I think I should prepare the statements in advance, but it will help now to make the change smooter.

Should something like

    let mut lp = Core::new().unwrap();
    let future = SqlConnection::connect(lp.handle(), connection_string.as_str())
    .and_then(|conn| {
        conn.query( "
        INSERT INTO [dbo].[Users]
            ([Email]
            ,[Token]
            ,[UserName])
        VALUES
            (@P1
            ,@P2
            ,@P3)" , &[ &email, &token, &username]  ).for_each_row( handle_row_no_value )
    } );
     lp.run(future).unwrap();

then work? I probably again overlooked something very simple, but I am getting 

`'query: unexpected token: DoneProc(TokenDone { status: , cur_cmd: 224, done_rows: 0 })'`

Thanks!

**Comment by steffengy** [comment]
Can't spot anything wrong in your usage there, likely a oversight on my part.
I'll look into it later.

**Comment by steffengy** [comment]
Actually the issue seems to be that you use `query` insteadof `exec` for that specific case.
(You're not querying but simply executing a SQL statement that doesn't return anything)

**Comment by davidpodhola** [comment]
So true! Anyway I will probably return the `SCOPE_IDENTITY()` here anyway to see what is going on. Thanks!

Will keep this open until all the statements are changed.
